### PR TITLE
Jsonunification

### PR DESCRIPTION
**Pull request by joshuacox**
I think all of these files can be unified into a single json file, I've integrated the vagrant and gce folders and brought the results into the root directory, I integrated the amazon builder as well, but not sure how to integrate the other files, they might be best left as they are for examples to others who build their own.  I understand if this is not the way you want to go, but before I had realized you had a qemu builder in the gce folder I had done most of the work already with the vagrant directory.  Anyhow, my changes are here if you want them.

### CODE REVIEW

**Comment by cloudnautique** [comment]
Thanks! We will take a look. These configs grew fairly organically and definitely need to be refactored/cleaned up.

**Comment by joshuacox** [comment]
I'm always open to comments and/or suggestions, and will update the pull request accordingly

**Comment by joshuacox** [comment]
I'll close this pull request, squash, and make another, if someone ( @cloudnautique possibly) will help me get into the thing in singleuser mode, as you can see in https://github.com/rancherio/os/issues/358 I'm at a bit of a loss as to how to debug what went wrong.  And this is all an intermediary step, I've got a future plan where you supply URLs for some of the required resources, but I just want this step working first before I take it further.

**Comment by cloudnautique** [comment]
@joshuacox there isn't a single user mode exactly. If it appears to have network or if you have console, you can press `e` at the grub menu, and add `rancher.password=password` (Or whatever you like for a password) to the kernel args. When it boots up you'll be able to login with as the rancher user with the password you supplied.

**Comment by joshuacox** [comment]
that worked thank you @cloudnautique 

do you have any other comment on what I'm doing here?  I'd like to make my work applicable  to downstream users, hence my use of the Makefile to prompt for info which should NOT be committted to github.

**Pull request closed without merging**
